import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "public/MainStyle.css";

import Header from "./Header";
import Footer from "./Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "מחולל צוות פיד החדש!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="he" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <Header />
        <div className="flex-1 w-full flex flex-col">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
